on:
  pull_request:
    types: [opened, reopened, edited, synchronize, closed]
  push:
    branches:
      - 'master'
jobs:
  integrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Java Corretto 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
      - name: Run checkstyle
        run: mvn checkstyle:checkstyle
      - name: Run unit tests
        run: mvn test
  docker:
    needs: integrate
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "danieltmcc/tsg-innolab-cicd-api:${{ github.sha }}"
  modifygit:
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'Acuity-Inc/tsg-innolab-cncf-delivery-bakeoff'
          token: ${{ secrets.GIT_PASSWORD }}
      - name: modify the image
        run: |
          git config user.email me@danieltmc.com
          git config user.name danieltmc
          cd fluxcd/tech-challenge-ci-cd-api
          pwd
          cat tech-challenge-ci-cd-api-app.yaml
          pwd
          sed -i "s+danieltmcc/tsg-innolab-cicd-api.*+danieltmcc/tsg-innolab-cicd-api:$GITHUB_SHA+g" app2.yaml
          cat app2.yaml
          git add .
          git commit -m 'Done  by Github Actions   Job changemanifest: $GITHUB_SHA'
          git push origin main
        env:
          GIT_USERNAME: ${{ vars.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
